---
title: "Biomonitoring exposure"
author: "En-Hsuan Lu"
date: "2023-02-01"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(ggplot2)
library(ggpubr)
library(reshape2)
knitr::opts_chunk$set(echo = TRUE)
```

## input data

```{r data}
don.urine <- fread(file.path("InputData","don exposure.csv"))
BE.urine.df <- read.csv("Urine BE.samples.csv")
BE.blood.df <- read.csv("Blood BE.samples.csv")
```

##MOE

```{r random}
set.seed(1234)

BE50 <- ((BE.urine.df$bmd/1000)*BE.urine.df$Cavg_dose_a*BE.urine.df$U_Cavg_h.GM) /BE.urine.df$AF_interTD
sigma_intra <- log(BE.urine.df$Intra.GSD)

#Martins et al. (2019)
don.urine$exp <- don.urine$`PDI DON`*0.64
urine.q <- quantile(don.urine$exp, prob=c(0.5,0.95))
#Median: 0.134 ug/kg-d = 0.000134 mg/kg-d
#P95: 1.014 ug/kg-d = 0.001014 mg/kg-d
#P95/P50=7.567
#GM: 0.000134; GSD: 7.567^(1/1.96)=2.808216
mar_exp <- rlnorm(10000, meanlog = log(0.000134), sdlog=log(2.808216))
quantile(mar_exp, prob=c(0.5, 0.05, 0.95))
sigma_marexp <- log(2.808216)

n <- 100000
df <- data.frame(run=1:n, GM_moe=NA, GSD_moe=NA, zran=NA, sigma_intra=NA, MOE_1perc=NA, MOE_ran=NA, z_frac=NA)
for(i in 1:n){
  df$sigma_intra[i] <- sample(sigma_intra, 1, replace = TRUE)
  df$GM_moe[i] <- sample(BE50, 1, replace = TRUE)/0.000134
  df$GSD_moe[i] <- exp((df$sigma_intra[i]^2+sigma_marexp^2)^(1/2))
  df$zran[i] <- rnorm(1)
    
  df$MOE_1perc[i] <- df$GM_moe[i] * df$GSD_moe[i]^qnorm(0.01) #z score=2.3
  df$MOE_ran[i] <- df$GM_moe[i] * df$GSD_moe[i]^df$zran[i]
  df$z_frac[i] <- -log(df$GM_moe[i])/log(df$GSD_moe[i]) #1 = GM_moe * GSD_moe^z; z=fraction of population%
}

df_quan <- apply(df[2:8], 2, quantile, prob=c(0.5, 0.05, 0.95))
write.csv(df_quan, file="Martins et al (2019) population MOE quantile.csv")

##Wang et al. (2019) exposure
wang_exp <- rlnorm(10000, meanlog = log(0.0008572618), sdlog = log(3.09911))
quantile(wang_exp, prob=c(0.5, 0.05, 0.95))
sigma_wangexp <- log(3.09911)

n <- 100000
df.w <- data.frame(run=1:n, GM_moe=NA, GSD_moe=NA, zran=NA, sigma_intra=NA, MOE_1perc=NA, MOE_ran=NA, z_frac=NA)
for(i in 1:n){
  df.w$sigma_intra[i] <- sample(sigma_intra, 1, replace = TRUE)
  df.w$GM_moe[i] <- sample(BE50, 1, replace = TRUE)/0.0008572618
  df.w$GSD_moe[i] <- exp((df.w$sigma_intra[i]^2+sigma_wangexp^2)^(1/2))
  df.w$zran[i] <- rnorm(1)
    
  df.w$MOE_1perc[i] <- df.w$GM_moe[i] * df.w$GSD_moe[i]^qnorm(0.01)
  df.w$MOE_ran[i] <- df.w$GM_moe[i] * df.w$GSD_moe[i]^df.w$zran[i]
  df.w$z_frac[i] <- -log(df.w$GM_moe[i])/log(df.w$GSD_moe[i])
}

df.w_quan <- apply(df.w[2:8], 2, quantile, prob=c(0.5, 0.05, 0.95))
write.csv(df.w_quan, file="Wang et al (2019) population MOE quantile.csv")
```

#urine UEi

```{r data}
datafolder <- "BBMD plot"
female_mice <- fread(file.path(datafolder,"don-female-parameters.csv"))
male_mice <- fread(file.path(datafolder,"don-male-parameters.csv"))
```

#set function for fraction of change

```{r function}
frachange.1 <- function(a,b,dose, dose.max = 1.5){
  resp <- (a*exp(b*dose/dose.max))/(a*exp(b*0))-1
  return(resp)
}
frachange.2 <- function(a,b,g,dose, dose.max = 1.5){
  resp <- (a*exp(b*((dose/dose.max)^g)))/(a*exp(b*(0^g)))-1
  return(resp)
}
frachange.3 <- function(a,b,c,dose, dose.max = 1.5){
  resp <- (a*(c-(c-1)*exp(-b*dose/dose.max)))/(a*(c-(c-1)*exp(-b*0)))-1
  return(resp)
}
frachange.4 <- function(a,b,c,g,dose, dose.max = 1.5){
  resp <- (a*(c-(c-1)*exp(-(b*dose/dose.max)^g)))/(a*(c-(c-1)*exp(-(b*0)^g)))-1
  return(resp)
}
frachange.5 <- function(a,b,c,g,dose, dose.max = 1.5){
  resp <- (a+(b*(dose/dose.max)^g)/(c^g+(dose/dose.max)^g))/(a+(b*0^g)/(c^g+0^g))-1
  return(resp)
}
frachange.6 <- function(a,b,g,dose, dose.max = 1.5){
  resp <- (a+b*((dose/dose.max)^g))/(a+b*(0^g))-1
  return(resp)
}
frachange.7 <- function(a,b,c,dose, dose.max = 1.5){
  resp <- (a+(b*dose/dose.max)/(c+dose/dose.max))/(a+(b*0)/(c+0))-1
  return(resp)
}
frachange.8 <- function(a,b,dose, dose.max = 1.5){
  resp <- (a+b*dose/dose.max)/(a+b*0)-1
  return(resp)
}
```

### Martins et al. (2019)

```{r random}
set.seed(1234)

ue <- rlnorm(10000, meanlog = log(0.000134), sdlog=log(2.808216))

yran<-numeric() # blank 
npop <- length(ue)
zrand <- rnorm(npop) # npop random individuals
for (j in 1:length(ue)) {
  y<-numeric() # blank 
  #for (k in 1:npop) {
    z_i <- zrand[j]
    AED <- (ue[j] * BE.urine.df$AF_interTD * ((BE.urine.df$Intra.GSD)^z_i))/(BE.urine.df$Cavg_dose_a*BE.urine.df$U_Cavg_h.GM)
    
    #model weight
    w_k_female <- c(0.271, 0.077, 0.216, 0.052, 0.058, 0.031, 0.174, 0.12)
    w_k_female <- w_k_female/sum(w_k_female) # Make sure adds up to 1
    w_k_female_cum <- cumsum(w_k_female) # Cumulative
    w_k_male <- c(0.224, 0.12, 0.09, 0.064, 0.065, 0.11, 0.058, 0.27)
    w_k_male <- w_k_male/sum(w_k_male) # Make sure adds up to 1
    w_k_male_cum <- cumsum(w_k_male) # Cumulative
    
    w_k5000_female_cum <- c(0,round(5000*w_k_female_cum)) # start/end index numbers
    w_k5000_male_cum <- 5000+c(0,round(5000*w_k_male_cum)) # start/end index numbers
    
    w_k5000_female <- diff(w_k5000_female_cum) # Difference is size
    w_k5000_male <- diff(w_k5000_male_cum) # Difference is size
    
    samp.parms.1 <- female_mice[sample(c(1:15000), size=w_k5000_female[1]),]
    samp.parms.2 <- female_mice[sample(c(15001:30000), size=w_k5000_female[2]),]
    samp.parms.3 <- female_mice[sample(c(30001:45000), size=w_k5000_female[3]),]
    samp.parms.4 <- female_mice[sample(c(45001:60000), size=w_k5000_female[4]),]
    samp.parms.5 <- female_mice[sample(c(60001:75000), size=w_k5000_female[5]),]
    samp.parms.6 <- female_mice[sample(c(75001:90000), size=w_k5000_female[6]),]
    samp.parms.7 <- female_mice[sample(c(90001:105000), size=w_k5000_female[7]),]
    samp.parms.8 <- female_mice[sample(c(105001:120000), size=w_k5000_female[8]),]
    
    # Use subsamples of AED
    y_female <- c(
      frachange.1(a=samp.parms.1$a, b=samp.parms.1$b, dose=AED[(1+w_k5000_female_cum[1]):w_k5000_female_cum[2]])
      ,frachange.2(a=samp.parms.2$a, b=samp.parms.2$b, g=samp.parms.2$g, dose=AED[(1+w_k5000_female_cum[2]):w_k5000_female_cum[3]])
      ,frachange.3(a=samp.parms.3$a, b=samp.parms.3$b, c=samp.parms.3$c, dose=AED[(1+w_k5000_female_cum[3]):w_k5000_female_cum[4]])
      ,frachange.4(a=samp.parms.4$a, b=samp.parms.4$b, c=samp.parms.4$c, g=samp.parms.4$g, dose=AED[(1+w_k5000_female_cum[4]):w_k5000_female_cum[5]])
      ,frachange.5(a=samp.parms.5$a, b=samp.parms.5$b, c=samp.parms.5$c, g=samp.parms.5$g, dose=AED[(1+w_k5000_female_cum[5]):w_k5000_female_cum[6]])
      ,frachange.6(a=samp.parms.6$a, b=samp.parms.6$b, g=samp.parms.6$g, dose=AED[(1+w_k5000_female_cum[6]):w_k5000_female_cum[7]])
      ,frachange.7(a=samp.parms.7$a, b=samp.parms.7$b, c=samp.parms.7$c, dose=AED[(1+w_k5000_female_cum[7]):w_k5000_female_cum[8]])
      ,frachange.8(a=samp.parms.8$a, b=samp.parms.8$b, dose=AED[(1+w_k5000_female_cum[8]):w_k5000_female_cum[9]])
    )
    
    samp.parms.1 <- male_mice[sample(c(1:15000), size=w_k5000_male[1]),]
    samp.parms.2 <- male_mice[sample(c(15001:30000), size=w_k5000_male[2]),]
    samp.parms.3 <- male_mice[sample(c(30001:45000), size=w_k5000_male[3]),]
    samp.parms.4 <- male_mice[sample(c(45001:60000), size=w_k5000_male[4]),]
    samp.parms.5 <- male_mice[sample(c(60001:75000), size=w_k5000_male[5]),]
    samp.parms.6 <- male_mice[sample(c(75001:90000), size=w_k5000_male[6]),]
    samp.parms.7 <- male_mice[sample(c(90001:105000), size=w_k5000_male[7]),]
    samp.parms.8 <- male_mice[sample(c(105001:120000), size=w_k5000_male[8]),]
    
    y_male <- c(
      frachange.1(a=samp.parms.1$a, b=samp.parms.1$b, dose=AED[(1+w_k5000_male_cum[1]):w_k5000_male_cum[2]])
      ,frachange.2(a=samp.parms.2$a, b=samp.parms.2$b, g=samp.parms.2$g, dose=AED[(1+w_k5000_male_cum[2]):w_k5000_male_cum[3]])
      ,frachange.3(a=samp.parms.3$a, b=samp.parms.3$b, c=samp.parms.3$c, dose=AED[(1+w_k5000_male_cum[3]):w_k5000_male_cum[4]])
      ,frachange.4(a=samp.parms.4$a, b=samp.parms.4$b, c=samp.parms.4$c, g=samp.parms.4$g, dose=AED[(1+w_k5000_male_cum[4]):w_k5000_male_cum[5]])
      ,frachange.5(a=samp.parms.5$a, b=samp.parms.5$b, c=samp.parms.5$c, g=samp.parms.5$g, dose=AED[(1+w_k5000_male_cum[5]):w_k5000_male_cum[6]])
      ,frachange.6(a=samp.parms.6$a, b=samp.parms.6$b, g=samp.parms.6$g, dose=AED[(1+w_k5000_male_cum[6]):w_k5000_male_cum[7]])
      ,frachange.7(a=samp.parms.7$a, b=samp.parms.7$b, c=samp.parms.7$c, dose=AED[(1+w_k5000_male_cum[7]):w_k5000_male_cum[8]])
      ,frachange.8(a=samp.parms.8$a, b=samp.parms.8$b, dose=AED[(1+w_k5000_male_cum[8]):w_k5000_male_cum[9]])
    )
    y <- c(y_female,y_male)
  yran <- cbind(yran,y)
}
yran<-as.data.frame(yran)
names(yran) <- paste("ue",1:length(ue),sep=".")

yranpop <- as.data.frame(apply(yran, 1, sample, size=1))
colnames(yranpop) <- "random"

ymean <- as.data.frame(apply(yran,1,mean))
colnames(ymean) <- "mean"

y1perc <- as.data.frame(apply(yran,1,quantile,prob=0.01))
colnames(y1perc) <- "1%pop"

y5perc <- as.data.frame(apply(yran,1,quantile,prob=0.05))
colnames(y5perc) <- "5%pop"

ymed <- as.data.frame(apply(yran,1,quantile,prob=0.5))
colnames(ymed) <- "50%pop"

y95perc <- as.data.frame(apply(yran,1,quantile,prob=0.95))
colnames(y95perc) <- "95%pop"

y99perc <- as.data.frame(apply(yran,1,quantile,prob=0.99))
colnames(y99perc) <- "99%pop"

yran.df <- cbind(yranpop, ymean, y1perc, y5perc, ymed, y95perc, y99perc)
write.csv(yran.df, file="Percent Martins et al (2019) population UE fraction of response.csv", row.names=FALSE)
```

### Wang et al. 2019

```{r random}
set.seed(1234)

w_ue <- rlnorm(10000, meanlog = log(0.0008572618), sdlog = log(3.09911))

yran<-numeric() # blank 
npop <- length(w_ue)
zrand <- rnorm(npop) # npop random individuals
for (j in 1:length(w_ue)) {
  y<-numeric() # blank 
  #for (k in 1:npop) {
    z_i <- zrand[j]
    AED <- (w_ue[j] * BE.urine.df$AF_interTD * ((BE.urine.df$Intra.GSD)^z_i))/(BE.urine.df$Cavg_dose_a*BE.urine.df$U_Cavg_h.GM)
    
    #model weight
    w_k_female <- c(0.271, 0.077, 0.216, 0.052, 0.058, 0.031, 0.174, 0.12)
    w_k_female <- w_k_female/sum(w_k_female) # Make sure adds up to 1
    w_k_female_cum <- cumsum(w_k_female) # Cumulative
    w_k_male <- c(0.224, 0.12, 0.09, 0.064, 0.065, 0.11, 0.058, 0.27)
    w_k_male <- w_k_male/sum(w_k_male) # Make sure adds up to 1
    w_k_male_cum <- cumsum(w_k_male) # Cumulative
    
    w_k5000_female_cum <- c(0,round(5000*w_k_female_cum)) # start/end index numbers
    w_k5000_male_cum <- 5000+c(0,round(5000*w_k_male_cum)) # start/end index numbers
    
    w_k5000_female <- diff(w_k5000_female_cum) # Difference is size
    w_k5000_male <- diff(w_k5000_male_cum) # Difference is size
    
    samp.parms.1 <- female_mice[sample(c(1:15000), size=w_k5000_female[1]),]
    samp.parms.2 <- female_mice[sample(c(15001:30000), size=w_k5000_female[2]),]
    samp.parms.3 <- female_mice[sample(c(30001:45000), size=w_k5000_female[3]),]
    samp.parms.4 <- female_mice[sample(c(45001:60000), size=w_k5000_female[4]),]
    samp.parms.5 <- female_mice[sample(c(60001:75000), size=w_k5000_female[5]),]
    samp.parms.6 <- female_mice[sample(c(75001:90000), size=w_k5000_female[6]),]
    samp.parms.7 <- female_mice[sample(c(90001:105000), size=w_k5000_female[7]),]
    samp.parms.8 <- female_mice[sample(c(105001:120000), size=w_k5000_female[8]),]
    
    # Use subsamples of AED
    y_female <- c(
      frachange.1(a=samp.parms.1$a, b=samp.parms.1$b, dose=AED[(1+w_k5000_female_cum[1]):w_k5000_female_cum[2]])
      ,frachange.2(a=samp.parms.2$a, b=samp.parms.2$b, g=samp.parms.2$g, dose=AED[(1+w_k5000_female_cum[2]):w_k5000_female_cum[3]])
      ,frachange.3(a=samp.parms.3$a, b=samp.parms.3$b, c=samp.parms.3$c, dose=AED[(1+w_k5000_female_cum[3]):w_k5000_female_cum[4]])
      ,frachange.4(a=samp.parms.4$a, b=samp.parms.4$b, c=samp.parms.4$c, g=samp.parms.4$g, dose=AED[(1+w_k5000_female_cum[4]):w_k5000_female_cum[5]])
      ,frachange.5(a=samp.parms.5$a, b=samp.parms.5$b, c=samp.parms.5$c, g=samp.parms.5$g, dose=AED[(1+w_k5000_female_cum[5]):w_k5000_female_cum[6]])
      ,frachange.6(a=samp.parms.6$a, b=samp.parms.6$b, g=samp.parms.6$g, dose=AED[(1+w_k5000_female_cum[6]):w_k5000_female_cum[7]])
      ,frachange.7(a=samp.parms.7$a, b=samp.parms.7$b, c=samp.parms.7$c, dose=AED[(1+w_k5000_female_cum[7]):w_k5000_female_cum[8]])
      ,frachange.8(a=samp.parms.8$a, b=samp.parms.8$b, dose=AED[(1+w_k5000_female_cum[8]):w_k5000_female_cum[9]])
    )
    
    samp.parms.1 <- male_mice[sample(c(1:15000), size=w_k5000_male[1]),]
    samp.parms.2 <- male_mice[sample(c(15001:30000), size=w_k5000_male[2]),]
    samp.parms.3 <- male_mice[sample(c(30001:45000), size=w_k5000_male[3]),]
    samp.parms.4 <- male_mice[sample(c(45001:60000), size=w_k5000_male[4]),]
    samp.parms.5 <- male_mice[sample(c(60001:75000), size=w_k5000_male[5]),]
    samp.parms.6 <- male_mice[sample(c(75001:90000), size=w_k5000_male[6]),]
    samp.parms.7 <- male_mice[sample(c(90001:105000), size=w_k5000_male[7]),]
    samp.parms.8 <- male_mice[sample(c(105001:120000), size=w_k5000_male[8]),]
    
    y_male <- c(
      frachange.1(a=samp.parms.1$a, b=samp.parms.1$b, dose=AED[(1+w_k5000_male_cum[1]):w_k5000_male_cum[2]])
      ,frachange.2(a=samp.parms.2$a, b=samp.parms.2$b, g=samp.parms.2$g, dose=AED[(1+w_k5000_male_cum[2]):w_k5000_male_cum[3]])
      ,frachange.3(a=samp.parms.3$a, b=samp.parms.3$b, c=samp.parms.3$c, dose=AED[(1+w_k5000_male_cum[3]):w_k5000_male_cum[4]])
      ,frachange.4(a=samp.parms.4$a, b=samp.parms.4$b, c=samp.parms.4$c, g=samp.parms.4$g, dose=AED[(1+w_k5000_male_cum[4]):w_k5000_male_cum[5]])
      ,frachange.5(a=samp.parms.5$a, b=samp.parms.5$b, c=samp.parms.5$c, g=samp.parms.5$g, dose=AED[(1+w_k5000_male_cum[5]):w_k5000_male_cum[6]])
      ,frachange.6(a=samp.parms.6$a, b=samp.parms.6$b, g=samp.parms.6$g, dose=AED[(1+w_k5000_male_cum[6]):w_k5000_male_cum[7]])
      ,frachange.7(a=samp.parms.7$a, b=samp.parms.7$b, c=samp.parms.7$c, dose=AED[(1+w_k5000_male_cum[7]):w_k5000_male_cum[8]])
      ,frachange.8(a=samp.parms.8$a, b=samp.parms.8$b, dose=AED[(1+w_k5000_male_cum[8]):w_k5000_male_cum[9]])
    )
    y <- c(y_female,y_male)
  yran <- cbind(yran,y)
}
yran<-as.data.frame(yran)
names(yran) <- paste("w_ue",1:length(w_ue),sep=".")

yranpop <- as.data.frame(apply(yran, 1, sample, size=1))
colnames(yranpop) <- "random"

ymean <- as.data.frame(apply(yran,1,mean))
colnames(ymean) <- "mean"

y1perc <- as.data.frame(apply(yran,1,quantile,prob=0.01))
colnames(y1perc) <- "1%pop"

y5perc <- as.data.frame(apply(yran,1,quantile,prob=0.05))
colnames(y5perc) <- "5%pop"

ymed <- as.data.frame(apply(yran,1,quantile,prob=0.5))
colnames(ymed) <- "50%pop"

y95perc <- as.data.frame(apply(yran,1,quantile,prob=0.95))
colnames(y95perc) <- "95%pop"

y99perc <- as.data.frame(apply(yran,1,quantile,prob=0.99))
colnames(y99perc) <- "99%pop"

yran.df <- cbind(yranpop, ymean, y1perc, y5perc, ymed, y95perc, y99perc)
write.csv(yran.df, file="Percent Wang et al (2019) population UE fraction of response.csv", row.names=FALSE)
```

#density plot (Martins et al. 2019)

```{r ggplot}
random <- ggplot(yran.df, aes(x=random))+
  geom_density()+
  theme_bw()+
  ggtitle("Random individual")+
  xlab("Fraction of response (% BW change)")+
  theme(axis.title.y = element_blank())

mean <- ggplot(yran.df, aes(x=mean))+
  geom_density()+
  theme_bw()+
  ggtitle("Population mean")+
  xlab("Fraction of response (% BW change)")+
  theme(axis.title.y = element_blank())

perc01 <- ggplot(yran.df, aes(x=`1%pop`))+
  geom_density()+
  theme_bw()+
  ggtitle("1%ile of Population")+
  xlab("Fraction of response (% BW change)")+
  theme(axis.title.y = element_blank())

perc50 <- ggplot(yran.df, aes(x=`50%pop`))+
  geom_density()+
  theme_bw()+
  ggtitle("50%ile of Population")+
  xlab("Fraction of response (% BW change)")+
  theme(axis.title.y = element_blank())

perc99 <- ggplot(yran.df, aes(x=`99%pop`))+
  geom_density()+
  theme_bw()+
  ggtitle("99%ile of Population")+
  xlab("Fraction of response (% BW change)")+
  theme(axis.title.y = element_blank())

frac <- ggarrange(random, mean, perc01, perc50, perc99, nrow=5, ncol=1)
ggsave(frac, file = "Martins et al (2019) Density plot_Fraction of response.pdf", width=8, height=10)
```

#quantile

```{r quantile}
###Martins et al (2019)
yran.df.mar <- read.csv("Percent Martins et al (2019) population UE fraction of response.csv")
quan.mar <- apply(yran.df.mar, 2, quantile, prob=c(0.5, 0.05, 0.95))
write.csv(quan.mar, file="Quantiles of Martins et al (2019) population UE fraction of response.csv")

###Wang et al (2019)
yran.df.wang <- read.csv("Percent Wang et al (2019) population UE fraction of response.csv")
quan.wang <- apply(yran.df.wang, 2, quantile, prob=c(0.5, 0.05, 0.95))
write.csv(quan.wang, file="Quantiles of Wang et al (2019) population UE fraction of response.csv")
```

##boxplot

```{r ggplot}
###Martins et al (2019)
yran.df.mar <- read.csv("Percent Martins et al (2019) population UE fraction of response.csv")
melt.yran.mar <- melt(yran.df.mar[,1:7])

expboxplot.mar <- ggplot(melt.yran.mar, aes(x=value, y=variable))+
  geom_boxplot(aes(fill=variable),
               outlier.shape=NA,
               show.legend = FALSE)+
  scale_x_continuous(limits=c(-0.1,0), breaks = c(-0.10,-0.05, 0), labels = c("-10%","-5%","0"))+
  scale_y_discrete(limits=rev, labels = c("Population 99%","Population 95%","Population median","Population 5%","Populaion 1%","Population mean","Random individual"))+
  theme_bw()+
  xlab("Fraction of response (% BW change)")+
  theme(axis.title.y = element_blank())+
  geom_vline(xintercept = -0.05, linetype="dashed", color="red")

ggsave(expboxplot.mar, file="Boxplot Martins et al (2019) population UE Fraction of response.pdf", width=8, height=10)

###Wang et al (2019)
yran.df.wang <- read.csv("Percent Wang et al (2019) population UE fraction of response.csv")
melt.yran.wang <- melt(yran.df.wang[,1:7])

expboxplot.wang <- ggplot(melt.yran.wang, aes(x=value, y=variable))+
  geom_boxplot(aes(fill=variable),
               outlier.shape=NA,
               show.legend = FALSE)+
  scale_x_continuous(limits=c(-0.1,0), breaks = c(-0.10,-0.05, 0), labels = c("-10%","-5%","0"))+
  scale_y_discrete(limits=rev, labels = c("Population 99%","Population 95%","Population median","Population 5%","Populaion 1%","Population mean","Random individual"))+
  theme_bw()+
  xlab("Fraction of response (% BW change)")+
  theme(axis.title.y = element_blank())+
  geom_vline(xintercept = -0.05, linetype="dashed", color="red")

ggsave(expboxplot.wang, file="Boxplot Wang et al (2019) population UE Fraction of response.pdf", width=8, height=10)
```

##compare with TDI values

```{r density}
set.seed(1234)
#Martins et al. (2019) population
pdi <- quantile(don.urine$`PDI DON`, prob=c(0.5,0.95))
#Median: 0.21 ug/kg-d = 0.00021 mg/kg-d
#P95: 1.58 ug/kg-d = 0.00158 mg/kg-d
#P95/P50=7.52381
#GM: 0.00021; GSD: 7.52381^(1/1.96)=2.800027
pdi_m <- rlnorm(10000, meanlog = log(0.00021), sdlog=log(2.800027))
quantile(pdi_m, prob=c(0.5, 0.05, 0.95))
d_m <- ecdf (pdi_m)
m <- 100*c(1-d_m(0.001), 1-d_m(0.00044), 1-d_m(0.00137))

#Wang et al. (2019) population
#Table 2. Estimated dietary DON intakes of the subjects. (Henan)
#Mean: 1.82 ug/kg bw/day = 0.00182 mg/kg bw/day
#SD: 2.10 ug/kg bw/day = 0.0021 mg/kg bw/day
#Q1: 0.00182-(0.675*0.0021)=0.0004025 mg/kg bw/day
#Q3: 0.00182+(0.675*0.0021)=0.0032375 mg/kg bw/day
#GM: (0.0032375*0.0004025)^(1/2) = 0.001141531 mg/kg bw/day
#GSD: (0.0032375/0.0004025)^(1/(qnorm(0.75)-qnorm(0.25))) = 4.690364
intake_w <- rlnorm(10000, meanlog = log(0.001141531), sdlog = log(4.690364))
quantile(intake_w, prob=c(0.5, 0.05, 0.95))
d_w <- ecdf(intake_w)
w <- 100*c(1-d_w(0.001), 1-d_w(0.00044), 1-d_w(0.00137))

perc_overtdi <- data.frame(m, w)
perc_overtdi$TDI <- c("EFSA","WHO/IPCS","Prob TDI")
write.csv(perc_overtdi, file="percent of population over TDI.csv", row.names = FALSE)
```
